/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialogLogin: typeof import('./src/components/TheDialogLogin.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheViewLabel: typeof import('./src/components/TheViewLabel.vue')['default']
    TheViewLabelProgress: typeof import('./src/components/TheViewLabelProgress.vue')['default']
    TheViewSelectors: typeof import('./src/components/TheViewSelectors.vue')['default']
    TheWidgetSearch: typeof import('./src/components/TheWidgetSearch.vue')['default']
    VDataEntry: typeof import('./src/components/VDataEntry.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
    VSelector: typeof import('./src/components/VSelector.vue')['default']
  }
}
