/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialogLogin: typeof import('./src/components/TheDialogLogin.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheViewLabel: typeof import('./src/components/TheViewLabel.vue')['default']
    TheViewLabelProgress: typeof import('./src/components/TheViewLabelProgress.vue')['default']
    TheViewSelectors: typeof import('./src/components/TheViewSelectors.vue')['default']
    TheWidgetSearch: typeof import('./src/components/TheWidgetSearch.vue')['default']
    VConnectedTreeNode: typeof import('./src/components/VObjectInspector/components/VConnectedTreeNode.vue')['default']
    VDataEntry: typeof import('./src/components/VDataEntry.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VInteractive: typeof import('./src/components/VObjectInspector/stories/VInteractive.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
    VObjectInspector: typeof import('./src/components/VObjectInspector/index.vue')['default']
    VObjectLabel: typeof import('./src/components/VObjectInspector/components/VObjectLabel.vue')['default']
    VObjectPreview: typeof import('./src/components/VObjectInspector/components/VObjectPreview.vue')['default']
    VObjectRootLabel: typeof import('./src/components/VObjectInspector/components/VObjectRootLabel.vue')['default']
    VObjectValue: typeof import('./src/components/VObjectInspector/components/VObjectValue.vue')['default']
    VSelector: typeof import('./src/components/VSelector.vue')['default']
    VTreeNode: typeof import('./src/components/VObjectInspector/components/VTreeNode.vue')['default']
    VTreeView: typeof import('./src/components/VObjectInspector/components/VTreeView.vue')['default']
  }
}
